### ISSUE TITLE
Feature request: add flash command

### ISSUE THREAD

**Issue by sscobici** [oracle/rwloadsim#3]
Hi,
I'd like to request a new command to be added "flash" that would allow to flash pending arrays data without committing a transaction.
We'd like to emulate insert and read inserted data in the same transaction and have a single commit at the end.
Currently there is a need to commit transaction after insert operation to force flushing pending arrays data from the client.

**Comment by bengsig** [comment]
That should not be too hard to implement, so this is something I will consider.

**Comment by bengsig** [comment]
Done. It will be available in the up-coming 3.0.1 release. If you are compiling yourself, download the latest master branch and compile.
